Repository nirum-lang/nirum, pull requests merged in 2018-07, with the labels that each got.

#288 Table syntax extension on docstrings
  CHANGES.md
  package.yaml
  src/Nirum/Docs.hs
  src/Nirum/Docs/Html.hs
  src/Nirum/Docs/ReStructuredText.hs
  test/Nirum/Docs/HtmlSpec.hs
  test/Nirum/Docs/ReStructuredTextSpec.hs
  test/Nirum/DocsSpec.hs
Labels: cat:lang, cmp:compiler, cmp:frontend, target:docs, typ:enhance

#289 Upgrade to Stackage LTS Haskell 12.0
  .hlint.yaml
  CHANGES.md
  README.md
  appveyor.yml
  package.yaml
  stack.yaml
Labels: cat:dist, typ:enhance

#291 Write about lint and chagelog on CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cat:docs
